---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "methyl-gkenamespace-lab-nginx"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "methyl-gkeapplication-lab-nginx"
  namespace: "methyl-gkenamespace-lab-nginx"
  labels:
    app: "methyl-gkeapplication-lab-nginx"
    stack: "methyl"
    environment: "lab"
    lab: "kubernetesengine"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "methyl-gkeapplication-lab-nginx"
      stack: "methyl"
      environment: "lab"
      lab: "kubernetesengine"
  template:
    metadata:
      labels:
        app: "methyl-gkeapplication-lab-nginx"
        stack: "methyl"
        environment: "lab"
        lab: "kubernetesengine"
    spec:
      containers:
      - name: "nginx"
        image: "nginx:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "methyl-gkeapplication-lab-nginx-hpa"
  namespace: "methyl-gkenamespace-lab-nginx"
  labels:
    app: "methyl-gkeapplication-lab-nginx"
    stack: "methyl"
    environment: "lab"
    lab: "kubernetesengine"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "methyl-gkeapplication-lab-nginx"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
